# Generated by Django 5.0.6 on 2024-06-19 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0002_blog_alter_category_options_alter_product_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["-created_at", "-count_of_views"],
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
            },
        ),
    ]
