# Generated by Django 5.0.6 on 2024-06-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_blog_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="count_of_views",
            field=models.IntegerField(default=0, verbose_name="колличество просмотров"),
        ),
    ]
