# Generated by Django 5.0.6 on 2024-06-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_blog_count_of_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="count_of_views",
            field=models.PositiveIntegerField(
                default=0, verbose_name="колличество просмотров"
            ),
        ),
    ]
