# Generated by Django 4.2.2 on 2024-07-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category", "created_at", "updated_at", "price"],
                "permissions": [
                    ("can_cancel_publication", "Может отменять публикацию"),
                    ("can_edit_description", "Может редактировать описание"),
                    ("can_edit_category", "Может менять категорию"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
